#!/bin/bash
echo "renaming..."
i=0;  for j in *.gif;   do mv "$j" "$i.gif";  (( i++ ));   done
echo "rename completed"
echo "..."
echo "converting..."
for i in *.gif;  do ffmpeg -i "$i" "./SAIDA/${i%.*}.webp"; done
echo "completed"

