#!/bin/bash
echo "renaming..."
i=0;  for j in *.mp4;   do mv "$j" "$i.mp4";  (( i++ ));   done
echo "rename completed"
echo "..."
echo "converting..."
for i in *.mp4;  do ffmpeg -i "$i" "./SAIDA/Vid${i%.*}.webp"; done
echo "completed"

